In [34]:
import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv('svm.csv')

In [36]:
df

,src_ip,dst_ip,src_port,dst_port,src_mac,dst_mac,protocol,timestamp,flow_duration,flow_byts_s,...,fwd_blk_rate_avg,bwd_blk_rate_avg,fwd_seg_size_avg,bwd_seg_size_avg,cwe_flag_count,subflow_fwd_pkts,subflow_bwd_pkts,subflow_fwd_byts,subflow_bwd_byts,label
0,172.27.224.251,172.27.224.250,56936,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-08-23 14:14,1470147,1.024387e+03,...,19918.28396,0,60.0,60.75,0,17,8,1020,486,mitm
1,172.27.224.251,172.27.224.250,56937,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-08-23 14:14,1470153,1.024383e+03,...,23138.53456,0,60.0,60.75,0,17,8,1020,486,mitm
2,172.27.224.251,172.27.224.250,56938,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-08-23 14:14,1470055,1.024451e+03,...,20066.88963,0,60.0,60.75,0,17,8,1020,486,mitm
3,172.27.224.251,172.27.224.250,56939,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-08-23 14:14,1470106,1.024416e+03,...,23262.74978,0,60.0,60.75,0,17,8,1020,486,mitm
4,172.27.224.70,255.255.255.255,64381,1947,00:0c:29:9d:9e:9e,ff:ff:ff:ff:ff:ff,17,2018-08-23 14:14,0,0.000000e+00,...,0.00000,0,82.0,0.00,0,1,0,82,0,mitm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21482,172.27.224.251,172.27.224.250,50111,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-09-08 17:13,1470144,1.024389e+03,...,22773.72263,0,60.0,60.75,0,17,8,1020,486,nomal
21483,172.27.224.250,172.27.224.251,502,49904,00:80:f4:09:51:3b,48:5b:39:64:40:79,6,2018-09-08 17:13,8,1.500000e+07,...,0.00000,0,60.0,60.00,0,1,1,60,60,nomal
21484,172.27.224.251,172.27.224.250,50112,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-09-08 17:13,1470118,1.024408e+03,...,20030.81664,0,60.0,60.75,0,17,8,1020,486,nomal
21485,172.27.224.251,172.27.224.250,50113,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-09-08 17:14,1470102,1.024419e+03,...,23437.50000,0,60.0,60.75,0,17,8,1020,486,nomal
21486,172.27.224.251,172.27.224.250,50114,502,48:5b:39:64:40:79,00:80:f4:09:51:3b,6,2018-09-08 17:14,234137,4.894570e+03,...,19933.55482,0,60.0,61.50,0,15,4,900,246,nomal

In [37]:
df.describe()

,src_port,dst_port,protocol,flow_duration,flow_byts_s,flow_pkts_s,fwd_pkts_s,bwd_pkts_s,tot_fwd_pkts,tot_bwd_pkts,...,bwd_pkts_b_avg,fwd_blk_rate_avg,bwd_blk_rate_avg,fwd_seg_size_avg,bwd_seg_size_avg,cwe_flag_count,subflow_fwd_pkts,subflow_bwd_pkts,subflow_fwd_byts,subflow_bwd_byts
count,21487.000000,21487.000000,21487.000000,2.148700e+04,2.148700e+04,2.148700e+04,21487.000000,21487.000000,21487.000000,21487.000000,...,21487.0,21487.000000,21487.0,21487.000000,21487.000000,21487.0,21487.000000,21487.000000,21487.000000,21487.000000
mean,53981.731047,2079.141807,7.553218,5.174865e+06,4.971155e+05,8.285098e+03,4145.104683,4139.993127,28.082748,14.732722,...,0.0,18148.289899,0.0,70.869156,52.718367,0.0,28.082748,14.732722,1809.227673,1058.235119
std,13980.101077,8542.382285,3.830613,1.790915e+07,4.119740e+06,6.866235e+04,34330.869281,34331.484555,85.025424,51.756997,...,0.0,8989.238626,0.0,54.299439,21.683562,0.0,85.025424,51.756997,5431.250705,4063.420820
min,68.000000,67.000000,6.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,1.000000,0.000000,...,0.0,0.000000,0.0,60.000000,0.000000,0.0,1.000000,0.000000,60.000000,0.000000
25%,50520.500000,502.000000,6.000000,1.460140e+06,1.024373e+03,1.700487e+01,11.563312,5.441562,17.000000,8.000000,...,0.0,19837.232960,0.0,60.000000,60.750000,0.0,17.000000,8.000000,1020.000000,486.000000
50%,55507.000000,502.000000,6.000000,1.470109e+06,1.024401e+03,1.700532e+01,11.563619,5.441707,17.000000,8.000000,...,0.0,22362.385320,0.0,60.000000,60.750000,0.0,17.000000,8.000000,1020.000000,486.000000
75%,62371.000000,502.000000,6.000000,1.470146e+06,1.024443e+03,1.700603e+01,11.564099,5.441944,17.000000,8.000000,...,0.0,23458.646620,0.0,60.000000,60.750000,0.0,17.000000,8.000000,1020.000000,486.000000
max,65437.000000,65437.000000,17.000000,9.849586e+07,1.200000e+08,2.000000e+06,1000000.000000,1000000.000000,579.000000,582.000000,...,0.0,35135.135140,0.0,1039.000000,85.000000,0.0,579.000000,582.000000,36474.000000,36648.000000

In [38]:
df.shape

(21487, 85)

In [39]:
df.dtypes

src_ip              object
dst_ip              object
src_port             int64
dst_port             int64
src_mac             object
                     ...
subflow_fwd_pkts     int64
subflow_bwd_pkts     int64
subflow_fwd_byts     int64
subflow_bwd_byts     int64
label               object
Length: 85, dtype: object

In [40]:
df['label'].value_counts

<bound method IndexOpsMixin.value_counts of 0         mitm
1         mitm
2         mitm
3         mitm
4         mitm
         ...
21482    nomal
21483    nomal
21484    nomal
21485    nomal
21486    nomal
Name: label, Length: 21487, dtype: object>

In [41]:
df['label'] = df['label'].map({'mitm': 1, 'other': 0}).fillna(0)

In [42]:
df['label']

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
21482    0.0
21483    0.0
21484    0.0
21485    0.0
21486    0.0
Name: label, Length: 21487, dtype: float64

In [43]:
train_data:int=df.drop(columns = [
    'src_ip','dst_ip','src_mac','dst_mac','timestamp','fwd_psh_flags','bwd_psh_flags', 
    'fwd_urg_flags','bwd_urg_flags','syn_flag_cnt','rst_flag_cnt','psh_flag_cnt','ack_flag_cnt','urg_flag_cnt','ece_flag_cnt','label'],axis=1)
label_data:int=df['label']

In [44]:
label_data

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
21482    0.0
21483    0.0
21484    0.0
21485    0.0
21486    0.0
Name: label, Length: 21487, dtype: float64

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(train_data,label_data,test_size=0.20,random_state=2202)

In [46]:
x_train.shape

(17189, 69)

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler=StandardScaler()
X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(x_test)

In [49]:
x_train

,src_port,dst_port,protocol,flow_duration,flow_byts_s,flow_pkts_s,fwd_pkts_s,bwd_pkts_s,tot_fwd_pkts,tot_bwd_pkts,...,bwd_pkts_b_avg,fwd_blk_rate_avg,bwd_blk_rate_avg,fwd_seg_size_avg,bwd_seg_size_avg,cwe_flag_count,subflow_fwd_pkts,subflow_bwd_pkts,subflow_fwd_byts,subflow_bwd_byts
10743,62337,502,6,1470154,1.024382e+03,17.005021,11.563414,5.441607,17,8,...,0,20233.46304,0,60.0,60.75,0,17,8,1020,486
19980,65189,502,6,1470100,1.024420e+03,17.005646,11.563839,5.441807,17,8,...,0,19706.92269,0,60.0,60.75,0,17,8,1020,486
8243,49284,502,6,1470157,1.024380e+03,17.004987,11.563391,5.441596,17,8,...,0,20233.46304,0,60.0,60.75,0,17,8,1020,486
9515,138,138,17,26212485,1.869338e+01,0.076300,0.076300,0.000000,2,0,...,0,0.00000,0,245.0,0.00,0,2,0,490,0
5293,55175,502,6,1460064,1.031462e+03,17.122537,11.643325,5.479212,17,8,...,0,26521.59130,0,60.0,60.75,0,17,8,1020,486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,57329,502,6,1470113,1.024411e+03,17.005495,11.563737,5.441759,17,8,...,0,22807.01754,0,60.0,60.75,0,17,8,1020,486
4773,502,54341,6,7,1.714286e+07,285714.285700,142857.142900,142857.142900,1,1,...,0,0.00000,0,60.0,60.00,0,1,1,60,60
3504,53738,502,6,1470073,1.024439e+03,17.005958,11.564052,5.441907,17,8,...,0,23508.13743,0,60.0,60.75,0,17,8,1020,486
2345,52784,502,6,1460131,1.031414e+03,17.121751,11.642791,5.478960,17,8,...,0,23831.34739,0,60.0,60.75,0,17,8,1020,486
18899,64348,502,6,1460133,1.031413e+03,17.121728,11.642775,5.478953,17,8,...,0,25382.36251,0,60.0,60.75,0,17,8,1020,486

In [50]:
y_train

10743    0.0
19980    0.0
8243     1.0
9515     1.0
5293     1.0
        ...
495      1.0
4773     1.0
3504     1.0
2345     1.0
18899    0.0
Name: label, Length: 17189, dtype: float64

In [57]:
from sklearn.svm import SVC
svm=SVC(kernel='linear',C=100)
svm.fit(X_train,y_train)

SVC(C=100, kernel='linear')

In [58]:
y_pred_test = svm.predict(X_test)

In [59]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Accuracy 계산
accuracy = accuracy_score(y_test, y_pred_test)
print(f"Accuracy: {accuracy:.4f}")

# Precision 계산
precision = precision_score(y_test, y_pred_test)
print(f"Precision: {precision:.4f}")

# Recall 계산
recall = recall_score(y_test, y_pred_test)
print(f"Recall: {recall:.4f}")

# F1 Score 계산
f1 = f1_score(y_test, y_pred_test)
print(f"F1 Score: {f1:.4f}")

Accuracy: 0.8074
Precision: 0.8000
Recall: 0.7698
F1 Score: 0.7846

In [60]:
from sklearn.decomposition import PCA
# PCA를 통해 차원 축소
pca = PCA(n_components=2)
train_data = pca.fit_transform(train_data)

# 차원 축소된 데이터를 DataFrame으로 변환
train_data = pd.DataFrame(train_data, columns=["col1", "col2"])

In [62]:
train_data

               col1           col2
0     -5.610732e+06 -334421.259815
1     -5.610888e+06 -335284.760663
2     -5.610570e+06 -334324.966303
3     -5.610844e+06 -334676.017359
4     -8.195629e+06 -425401.987249
...             ...            ...
21482 -5.610508e+06 -334556.004057
21483 -8.276384e+06 -473583.542490
21484 -5.610513e+06 -334399.837658
21485 -5.610863e+06 -334711.155305
21486 -7.868872e+06 -222641.909070

[21487 rows x 2 columns]